# Generated by Django 4.2.4 on 2023-08-18 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0006_service_taxonomies'),
        ('basket', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='country',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='content_id',
        ),
        migrations.RemoveField(
            model_name='basketitem',
            name='content_type',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Catalogue.service'),
            preserve_default=False,
        ),
    ]
