# Generated by Django 4.2.4 on 2023-08-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_remove_basket_country_remove_basketitem_content_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketitem',
            name='quantity',
        ),
    ]
