# Generated by Django 4.2.4 on 2023-08-06 13:12

from django.db import migrations, models
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0002_catalogue_created_by_catalogue_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='image',
            field=pictures.models.PictureField(aspect_ratios=[None], blank=True, breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, pixel_densities=[1, 2], upload_to='catalogue'),
        ),
    ]
