# Generated by Django 4.2.4 on 2023-08-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0005_service_servicetaxonomy_taxonomy_delete_catalogue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='taxonomies',
            field=models.ManyToManyField(related_name='services', through='Catalogue.ServiceTaxonomy', to='Catalogue.taxonomy'),
        ),
    ]
