# Generated by Django 4.2.4 on 2023-08-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_service_provider',
            new_name='is_staff',
        ),
    ]
