# Generated by Django 4.2.4 on 2023-09-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_admin_user_is_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='created',
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='address',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='verify_token',
        ),
        migrations.AlterField(
            model_name='address',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
