# Generated by Django 4.2.5 on 2023-11-11 10:16

from django.db import migrations
import pictures.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=pictures.models.PictureField(aspect_ratios=[None], blank=True, breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, file_types=['WEBP'], grid_columns=12, null=True, pixel_densities=[1, 2], upload_to='media/users'),
        ),
    ]
