# Generated by Django 4.2.5 on 2023-12-29 18:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogue', '0003_alter_fixiservice_client_and_more'),
        ('users', '0009_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='taxonomy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_providers', to='Catalogue.taxonomy'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
